{% set name = "mip" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mip-{{ version }}.tar.gz
  sha256: 7f6f0381cfe2c52c1b8640203da2cb56974b26e23950ddfb1a76b37d916f197e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.7,<3.12
    - cffi ==1.15.*

test:
  imports:
    - mip
  commands:
    - pip check
  requires:
    - pip

about:
  license: EPL-2.0
  license_file: LICENSE
  summary: Python tools for Modeling and Solving Mixed-Integer Linear Programs (MIPs)
  doc_url: https://python-mip.readthedocs.io
  dev_url: https://github.com/coin-or/python-mip

extra:
  recipe-maintainers:
    - JoOkuma
